use_frameworks!

target 'York_Example' do
  pod 'York', :path => '../'
end

target 'York_Tests' do
  pod 'York', :path => '../'
  pod 'AFNetworking', '3.1.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '3.0'
      end
  end
end
