# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.2
env: PRODUCT_NAME=York
language: objective-c
before_install:
- gem install cocoapods -v '= 0.38.0'
- pod install --project-directory=Example
script:
- xctool -workspace Example/York.xcworkspace -scheme York-Example test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
- pod lib lint
