# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.2

language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
before_install:
#- brew update
#- brew install xctool
#  gem install cocoapods -v '= 0.34.0'
- gem install cocoapods -v '= 0.38.0'
- pod install --project-directory=Example
script:
# - set -o pipefail && xcodebuild test -workspace Example/York.xcworkspace -scheme York-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
#- set -o pipefail && xcodebuild test -workspace Example/York.xcworkspace -scheme York-Example -sdk iphonesimulator -arch i386 test | xcpretty
# - xctool -project Example/York.xcworkspace -scheme 'York-Example' -configuration Debug -sdk iphonesimulator -arch i386 test
#- set -o pipefail && xcodebuild test -workspace Example/York.xcworkspace -scheme York-Example -sdk iphonesimulator -arch i386 test | xcpretty
#- set -o pipefail && xcodebuild test -workspace Example/York.xcworkspace -scheme York-Example -sdk iphonesimulator -configuration Release TEST_AFTER_BUILD=YES
#- xctool -project JLRoutes.xcodeproj -scheme 'JLRoutes' -configuration Debug -sdk iphonesimulator -arch i386 test
#- xctool -workspace Example/York.xcworkspace -scheme York-Example test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
- xctool -workspace Example/York.xcworkspace -scheme York-Example test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
- pod lib lint
