# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.2
language: objective-c
before_install:
- gem install cocoapods -v '= 0.39.0'
- pod install --project-directory=Example
script:
#- xcrun simctl list
- set -o pipefail
- xcodebuild -workspace Example/York.xcworkspace -scheme York test -sdk iphonesimulator9.2 -destination "platform=iOS Simulator,name=iPhone 6" | xcpretty -c
- pod lib lint
#- xctool -workspace Example/York.xcworkspace -scheme York clean build test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
#- pod lib lint
after_success:
- bash <(curl -s https://codecov.io/bash)
