# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.2
language: objective-c
before_install:
- ./install_swiftlint.sh
- gem install cocoapods -v '= 0.39.0'
- pod install --project-directory=Example
script:
- cd York/Classes
- swiftlint
- cd ..
- cd ..
- set -o pipefail
- xcodebuild -workspace Example/York.xcworkspace -scheme TravisCI test -sdk iphonesimulator9.2 -destination "platform=iOS Simulator,name=iPhone 6" | xcpretty -c
- pod lib lint
after_success:
- bash <(curl -s https://codecov.io/bash)
