# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8
language: objective-c
before_install:
- ./install_swiftlint.sh
- ./install_homebrew.sh
- gem install bundler
- bundle install
- bundle exec pod repo update > /dev/nil
- bundle exec pod install --project-directory=Example
script:
- cd Classes
- swiftlint
- cd ..
- set -o pipefail
- xcodebuild -workspace Example/York.xcworkspace -scheme TravisCI test -sdk iphonesimulator10.0 -destination "platform=iOS Simulator,name=iPhone 6" | xcpretty -c
- pod lib lint
after_success:
- bash <(curl -s https://codecov.io/bash)
